services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@api-db-test:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_ANON_ROLE: anon
    depends_on:
      - postgres
  postgres:
    container_name: api-test-db
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=api-test
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./db/api-test-database.sql:/docker-entrypoint-initdb.d/api-test-database.sql
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/